POST http://localhost:8080/kvstore HTTP/1.1
content-type: application/json

{
    "Key":3,
    "Value":"Taj"
}

###
PUT http://localhost:8080/kvstore HTTP/1.1
content-type: application/json

{
    "Key":3,
    "Value": "Car"
}

###
DELETE http://localhost:8080/kvstore?key=3 HTTP/1.1

###
GET http://localhost:8080/kvstore?key=3 HTTP/1.1